name: Example workflow for dotNET using Snyk CLI
on: push
jobs:
 security:
    permissions:
        actions: read
        contents: read
        security-events: write   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Restore dependencies
        run: dotnet restore ./TestCasesCurated.sln
      - name: Run Snyk CLI to check for vulnerabilities
        run: |
          snyk code test --all-projects --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
